#!/bin/bash

# Function to add record to text file
addRecord() {
	echo "Please fill out the following fields of information:"
	echo "NOTE: Do not use colons(:) in any of the data entries"
	read -p 'Name: ' userName
	read -p 'Address: ' userAddress
	read -p 'Phone: ' userPhone
	read -p 'Email: ' userEmail

	echo $userName:$userAddress:$userPhone:$userEmail >> database.txt
}

# Print is used to read contents of input file. 
print() {
	IFS=":"
	while read name address phone email;
	do
		echo $name 	$address 	$phone 		$email
	done <database.txt
}

#Function finds one or more records in database
find(){
DATABASE="database.txt"

echo "Enter a record to find: "
read input

RECORD=$(grep -i $input $DATABASE)

for line in "$RECORD"
do
	if [ $? == 1 ]; #a '1' indicates that no matches were found
	then
		echo "Could not find the requested record"
	else
		echo "Found the requested record: $line"
	fi
done
}

# Function updates record user
update(){
read -p "Please enter the first and last name on the file you wish to remove: " firstName
grep  "^$firstName" ./dataBase.txt
lnNmbr="grep -c \"^$firstName\" ./dataBase.txt "
eval $lnNmbr
read -p "Is this the file you wish to update?" data
if test "$data" = "y" 
	then grep -v "^$firstName" ./dataBase.txt > ./dataBaseHolder
	read -p "Enter new first and last name: " newName
	read -p "Enter new address: " newAdd
	read -p "Enter new phone: " newPhone
	read -p "Enter new email: " newEmail
	echo "$newName:$newAdd:$newPhone:$newEmail" >> ./dataBaseHolder
	mv ./dataBaseHolder ./dataBase.txt
	echo "working"
else
	echo "trying"
fi
echo "DataBase"
cat ./dataBase.txt
}


# Interative menu 
menu(){
echo "Welcome to my contact database, please select in the following menu:"
echo "(a) Find a record"
echo "(b) Add a new record"
echo "(c) Update a record"
echo "(d) Remove a record"
echo "(e) Display Contacts"
echo "(f) Quit"
echo "> Selection is:"

while :
do 
   read input
   case $input in 
      [aA])
         #call find record function
	 find
         break ;;
      [bB])
         #call Add new record function
         addRecord
         break ;;
      [cC])
         #call Update record function
	 update
         break ;;
      [dD])
         #call Remove record function
         break ;;
      [eE])
      	 #call print function
	 print
	 break;;
      [fF])
         echo "Thank you! Goodbye"
         exit ;; 
      *)
         echo "Sorry that isn't an option, select again.";;
   esac
done 
}
touch database.txt
echo "Name:Address:Phone:Email" >> database.txt
answer=1
while [ $answer -eq 1 ] 
do 
   menu
   echo "Would you like to select again(y/n)?"
   while :
   do   
      read response
      case $response in
         [yY]) answer=1 
            break ;;
         [nN]) answer=0 
            break ;;
         *) echo "Invalid response please enter again."
      esac
   done
done
echo "Thank you! Goodbye"
